### ISSUE TITLE
Remove course alerts

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#100]
We've talked a few times about this. Since I could find a corresponding issue, a new one was created here.

This feature:
https://dhcr.clarin-dariah.eu/follow#course-alert
is broken since more than 2 years.

Suggested before: remove completely.

Update:
The corresponding cron job (dhcr-subscriptions) which was suspended, has been removed today.

**Comment by patrickakk** [comment]
The decision can be found here: https://github.com/acdh-oeaw/dhcr-main/issues/15#issuecomment-1831470757

**Comment by patrickakk** [comment]
The course alerts have been completely removed from the menu, and the pages. As well the templates, controllers, models, tests, email templates and cron jobs has been removed.
TODO when this is in production:

- [x] Remove tables subscriptions and notifications from db

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer

Can you change the label to Done?

(You can see, in the test instance, in the menu and the pages that the feature has been removed)

**Comment by PixlTracer** [comment]
thanks!

**Comment by patrickakk** [comment]
Implemented in 2023-12.

Some remaining tasks needs to be done by me when this is in production.

**Comment by patrickakk** [comment]
Removed the 8 tables: countries_subscriptions, course_types_subscriptions, disciplines_subscriptions, languages_subscriptions, notifications, subscriptions,  subscriptions_tadirah_objects, subscriptions_tadirah_techniques.

Issued completed.
