### ISSUE TITLE
Yearly cleanup of pending account requests and invitations

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#101]
@PixlTracer @IvdL22 

After our successful cleanup round in Feb 2023 a year has already past. A look at the current status shows (in production):

**Accounts waiting for approval**
1 account, since  1 month, 2 days ago

**Pending invitations which are not valid anymore**
13 accounts

Can those be removed? Which one should we keep?

Note:
Information in this issue is public readable. Please do not write email addresses or names or any privacy related information here.

**Comment by PixlTracer** [comment]
dear Patrick, 
thank you for the sum-up; we are aware of the one pending account request, it is a special case and we are in contact with the account-applicant;
in regards to pending invites: I am fine with deleting them, since they are not valid anymore.
@IvdL22, do you agree?

**Comment by IvdL22** [comment]
@PixlTracer @patrickakk Anna, I agree with your suggestion. No updates regarding the pending account, I will send a reminder.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 
Thanks for the quick response. I'll do the following:

- [x] Remove 13 accounts

and then close the issue.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

The 13 outdated pending invitations have been removed.

Can you give an update on the user account, which is pending since 3 months, 2 weeks, 5 days ? What can we do with that?

**Comment by IvdL22** [comment]
@patrickakk I emailed the pending account but no reply. I will send a reminder.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

Thanks for the update. I'll close the issue.

Feel free to send an email if the account should be removed.
