### ISSUE TITLE
Change default zoom level and center to Europe

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#103]
@IvdL22 @PixlTracer 

In case a user doesn't allow access to their location, the map on the main page is set to a default zoom level and center point. What do you think of changing this to Europe as illustrated in the screenshots below?

# Current view
![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/8727007a-52a7-40b3-b028-01dd9724c0c3)

# New view
![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/6ecb0e86-f53c-4dbc-9e29-ce5dbacd69f3)

**Comment by IvdL22** [comment]
@patrickakk @PixlTracer I like the proposed view.

**Comment by patrickakk** [comment]
@IvdL22
Ok, then I'll make the changes.
@PixlTracer Do you also agree?

**Comment by PixlTracer** [comment]
agreed!

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

The feature is ready and can be found here:
https://test-dhcr.clarin-dariah.eu/

Can you change the label to Done if satisfied?

Note: Before the change, the user was asked to give access to their location. Since the additional benefit of giving access was small, I've removed this as well. Especially privacy minded users may like this. And the map is already centered on Europe, which covers the majority of courses and users?
Feel free the let me know if you think otherwise. The "old" behavior can be found in production.

**Comment by IvdL22** [comment]
Thank you @patrickakk

**Comment by patrickakk** [comment]
Implemented in 2024-06
