### ISSUE TITLE
Add explanation about new API url

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#104]
Currently the only API is production is v2. The documentation is still from v1. This might lead to misunderstanding when reading the documentation.

Current quick solution:
Add a note/explanation on the API v2 landing page.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

The problem description can be found on the top of this issue.

The implemented solution can be found here, under "Documentation":
https://test-dhcr.clarin-dariah.eu/api/v2/

Can you change the label to Done if satisfied?

**Comment by IvdL22** [comment]
@patrickakk Nice, thank you.

**Comment by patrickakk** [comment]
Implemented in 2024-05
