### ISSUE TITLE
Add 2 new bar charts to course statistics

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#105]
1. Create a bar chart of Courses per Country (countries on x-axis to fit presentation slide)
2. Create a bar chart of Courses per Education Type

The information is currently only available when clicking on "filter", see the photo's below. This means manual work is needed every time and it depends on the availability of the filter option.

![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/8612c2f6-d1f6-4d16-aac8-a78d04561dcb)

![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/365731d9-7e8e-4def-8ae5-3e667676f00e)

**Comment by patrickakk** [comment]
Preview of course counts per country:

![image](https://github.com/user-attachments/assets/820e12af-2317-46b3-b7ff-9c81e3be6121)

![image](https://github.com/user-attachments/assets/cccd8a26-72ca-4880-89c6-80ec4c32efab)

**Comment by patrickakk** [comment]
preview of course counts per education type:

![image](https://github.com/user-attachments/assets/adc39281-59c7-44fe-ac16-bfda85e62d2e)

**Comment by patrickakk** [comment]
@IvdL22
cc @PixlTracer 

The features we talked about a few months ago are ready.

When available, It can be found and tested here:
https://test-dhcr.clarin-dariah.eu/statistics/course-statistics

Note: unfortunately, at the moment, the deployment does not work. So it can't be tested and I'll mark the issue as "blocked" and send you an update, when it's available.

**Comment by patrickakk** [comment]
@IvdL22
cc @PixlTracer

The feature is now available in test, as explained above. Can you review it?

Does the type of chart suit what you need?
If necessary the bar charts could be "rotated" by 90 degrees easily. Bar chart / Column chart

**Comment by PixlTracer** [comment]
hi @patrickakk 
thank you for this!
The charts are just what we were looking for, I think it is a very nice feature that they indicate the absolute numbers when hovering over a column.
I'll set the label to done.

**Comment by patrickakk** [comment]
Implemented in 2024-11
