### ISSUE TITLE
Imprint text is missing

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#107]
@vronk 
On the info page, at the section imprint:
https://dhcr.clarin-dariah.eu/info#imprint
there was an imprint text shown.

Yesterday I noticed that it doesn't work any more. It loads the file specified below:

https://shared.acdh.oeaw.ac.at/acdh-common-assets/api/imprint.php?serviceID=7435

Do we need to update the link?

**Comment by vronk** [comment]
Yes, we need to update the link.
This should work by using https://imprint.acdh.oeaw.ac.at/7435

Check the doc of the imprint service:
https://github.com/acdh-oeaw/imprint-service

**Comment by patrickakk** [comment]
Implemented in 2024-07.

@IvdL22 @PixlTracer 
Can you change the label to Done, if you agree?

**Comment by IvdL22** [comment]
@patrickakk Done, thanks
