### ISSUE TITLE
Remove email addresses from API output

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#109]
(This was discussed last year, for some reason I couldn't find the issue, so here is a new one)

The courses output from the API contains also email addresses.

For privacy reasons, etc. I would recommend to remove them from the API output and only show on the web page at the course detail page.

**Comment by vronk** [comment]
Agree to remove email from API result.

**Comment by vronk** [comment]
If it is a matter of under an hour, let's do it now, otherwise postpone.

**Comment by patrickakk** [comment]
`Note: This can be reviewed when it's available in the test instance`

Possible urls to review:

- https://test-dhcr.clarin-dariah.eu/api/v2/courses/index
- https://test-dhcr.clarin-dariah.eu/api/v2/courses/view/6
- https://test-dhcr.clarin-dariah.eu/api/v2/courses/index?recent

**Comment by patrickakk** [comment]
@PixlTracer @IvdL22 

Can you review this? Urls can be found above.

**Comment by PixlTracer** [comment]
hi @patrickakk 
I've checked the following URLs:
- https://test-dhcr.clarin-dariah.eu/api/v2/courses/index - everything looks fine, no email (field) detected
- https://test-dhcr.clarin-dariah.eu/api/v2/courses/view/6 - ok too
- https://test-dhcr.clarin-dariah.eu/api/v2/courses/index?recent - ok too!

I'll set the label to done.
thank you!

**Comment by patrickakk** [comment]
Implemented in 2024-11
