### ISSUE TITLE
Required file missing

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#110]
The cron job gen_search_list.sh is not working correctly, altough it's runned.

The lines in the top of includes.sh result in an error, and exit. Therefore setting the php path, which is in the last lines, doesn't work and the whole job doesn't work.

The result is that the search bar doesn't show the autocomplete list and can't be used.

Temporarly fixed for now.
Additional action needed.

Edit: since it concerns the includes.sh it might apply to all cron jobs.

Edit 2024-10-22: Status update here: https://github.com/acdh-oeaw/dhcr-main/issues/110#issuecomment-2428638906

**Comment by patrickakk** [comment]
@vronk FYI

**Comment by patrickakk** [comment]
the error remains when running one of the cron jobs from the /src/Command folder and having that folder as current working directory

> ./review_reminders.sh 
cp: cannot stat '.user.ini': No such file or directory
./review_reminders.sh: line 8: bin/cake: No such file or directory

the error disappears when doing the same action from /

the search bar autocomplete works again. it's not clear why it didn't work before or why it's fixed now.

**Comment by patrickakk** [comment]
since it works for now, i'm closing the issue. we can open a new issue if the problem occurs again? change implemented in 2024-09.

**Comment by patrickakk** [comment]
Today the problem happened again. The search bar doesn't work, because the required file "search_list.json" is not available in the production container.

The logs in Rancher show that cron jobs are run, for example gen_search_list.sh and course_reminders.sh.
The actual emails sent also show that the course reminders job did run. So some cron jobs are working?

But still the required json file, which is generated by gen_search_list.sh is not available.

I have 3 detailed screenshot available and will send them to Dalibor per email. Since they are taken from the Rachner environment I'll not post them here.

Edit/update: Since I executed the job manually from the shell, it works again (for now).

Addition: The rancher logs do show an error, 2 minutes after the cron job did run (at 10:17:21) Message: Unable to retrieve some image pull secrets; attempting to pull the image may not succeed.

**Comment by patrickakk** [comment]
@dpancic Can you help to solve this?

**Comment by acdh** [comment]
According to line 39 in [GenSearchListCommand.php](https://github.com/acdh-oeaw/dhcr-main/blob/prod/src/Command/GenSearchListCommand.php) cronjob named dhcr-gen-search-list should create search_list.json in /webroot directory. The cronjob is doing it correctly. 

The app cannot reach and use  search_list.json because it is not located in the app container. 
The cronjob is executed in a separate container and does not have shared directories with the app.

The problem can be solved by creating PVC that will be shared between the cronjob and the container with the app.
The GenSearchListCommand.php should be reconfigured to store search_list.json in the mounted (shared) directory (for example /cronjob-output, and the app should be reconfigured to expect search_list.json in /cronjob-output directory.

The PVC named cronjob-output is created and mounted in the app and in all cronjob containers as /cronjob-output. 

@patrickakk please adjust the GenSearchListCommand.php and the app accordingly.

The error related to Gitlab secrets is false warning and unrelated to our deployment. We are not using Gitlab with this app. It can be ignored.

**Comment by patrickakk** [comment]
@dpancic 

Thank you for the solution and clear explanation.

Currently the /cronjob-output folder is in the root of the container. Is there a special reason for this? Would it be possible to use /workspace/cronjob-output ?

In that case all the paths are still inside the Git repo. That makes it easier compatible between (local) development and the deployment.

**Comment by patrickakk** [comment]
Implemented in 2024-09/2

The same needs to be done for GenSitemapCommand.php

**Comment by acdh** [comment]
@patrickakk /cronjob-output is moved to /workspace/cronjob-output in the app container and in all other cronjobs.
Please adjust all php scripts used by all DHCR cronjobs.

**Comment by patrickakk** [comment]
@acdh-ch  Thank you. All php scripts have been updated where necessary.

FYI: I've checked the timestamp of the search_list.json file and it was updated today, a few minutes ago, so everything seems to work fine now.

**Comment by patrickakk** [comment]
Adjusted things for sitemap.xml as well. Implemented in 2024-09/3

**Comment by patrickakk** [comment]
Status update: 
It seems that sitemap.xml is not updated. It's only created on deployment (through entrypoint.sh) The logs within the application show that the cronjob for update sitemap.xml did run, but the timestamp of the file in the folder cronjob-output shows that it's not updated.

@dpancic Can you help? Does the cronjob has access to the correct shared folder?

FYI: A few minutes ago, I did run the gen_sitemap.sh manually from the shell, so sitemap.xml now has the timestamp of today.

**Comment by patrickakk** [comment]
![241103_dhcr_sitemap_outdated](https://github.com/user-attachments/assets/61ebb178-edbe-4cdd-bdf8-a741cdd993bf)

**Comment by acdh** [comment]
@patrickakk the problem was caused by the typo related to the shared folder name in the cronjob yaml file.

**Comment by patrickakk** [comment]
screenshot of today, showing that sitemap.xml is updated:

![image](https://github.com/user-attachments/assets/9fd54999-9dca-4028-b871-6b0ece0336d6)

**Comment by patrickakk** [comment]
Implemented in 2024-09/3.

I'll close the issue (again) since everything seems to work fine now.
