### ISSUE TITLE
[Fault] Swiss Federal Institute of Technology Lausanne

### ISSUE THREAD

**Issue by StEvUgnIn** [acdh-oeaw/dhcr-main#111]
![image](https://github.com/user-attachments/assets/93bc7a72-f198-444b-8ae2-1bcf1bf40e49)

The following are courses part of the EPFL Master of Science MSc in Digital Humanities: see the following link https://www.epfl.ch/education/master/programs/digital-humanities/

I suggest to:
1. rename the French title ``École Polytechnique Fédérale de Lausanne`` into ``Swiss Federal Institute of Technology Lausanne``, and to
2. replace the entries in the screenshot by the following entry (name, date) `Master of Science MSc in Digital Humanities` - 4 semesters.

Edit: I have noticed I should contact the course director since they are the contributor in charge. You may close this issue, and I will contact them as soon as possible.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 
cc @StEvUgnIn
Could you check this with the course contributor and/or national moderator?

And close the issue if solved?

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 
REMINDER: Could you take a look at this? (See above)

**Comment by PixlTracer** [comment]
hi all, 
thank you @StEvUgnIn for the description, apologies for the late reply.

ad 1) I've renamed the institution to "Swiss Federal Institute of Technology Lausanne" as suggested, you can see the changes in production

ad 2) you had written 

> replace the entries in the screenshot by the following entry (name, date) Master of Science MSc in Digital Humanities - 4 semesters.

Unfortunately, we have to stick to the `education types` available:
<img width="544" alt="Screenshot_DHCR_EducationType" src="https://github.com/user-attachments/assets/a39c8f51-d7b6-489c-9325-2d63d410ef5f">

hence, @StEvUgnIn, you might as well add the info`Master of Science MSc in Digital Humanities - 4 semesters` into the course description field; 

I hope this was useful, let me, @IvdL22 & @patrickakk know in case we can assist you with any further inquiries. Alternatively, you may close this issue.
