### ISSUE TITLE
Review wording for Source URL?

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#115]
@IvdL22 @PixlTracer 

At the course detail page, for example here:
https://dhcr.clarin-dariah.eu/courses/view/384

There is an URL specified, see screenshot:
![image](https://github.com/user-attachments/assets/0cbb2ff8-aca5-4aac-9532-651292989865)

This URL links to a page at the institution website, which contains more information about the specified course.

I did receive feedback that the wording "Source URL" seems to be to unclear, to explain what is meant.

What do you think of updating this description?
Do you have suggestions?

**Comment by IvdL22** [comment]
@patrickakk Thank you for this. I think it should be ''Course URL". @PixlTracer Do you agree?

**Comment by patrickakk** [comment]
@PixlTracer REMINDER: Could you provide you opinion as well? (As requested by @IvdL22 )

**Comment by PixlTracer** [comment]
yes, agreed! please proceed, thank you @patrickakk

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

The change has been implemented:

![image](https://github.com/user-attachments/assets/ced2873b-3956-4f59-a4db-9fe010cb36c7)

And can be found here:
https://test-dhcr.clarin-dariah.eu/courses/view/384

In this case, I'm pretty sure that the result is, as expected ;)

Note: The course data itself is different, this is because the database in the test  instance is outdated.

Al tough, by still following our workflow, could you change the label to done, if agreed?

**Comment by IvdL22** [comment]
@patrickakk Thank you, Patrick! Done!

**Comment by patrickakk** [comment]
Implemented in 2024-12
