### ISSUE TITLE
Ubuntu-latest pipelines will use ubuntu-24.04 soon

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#117]
@acdh-ch 
Today's pipeline shows the following warning. Do we need to do something because of this?

> Deploy Docker image from the branch dev
> ubuntu-latest pipelines will use ubuntu-24.04 soon. For more details, see https://github.com/actions/runner-images/issues/10636

![image](https://github.com/user-attachments/assets/f2d423f5-98cf-4af2-8177-453e4d21fa70)

**Comment by acdh** [comment]
@patrickakk ubuntu image in the workflow is updated to ubuntu-24.04 and the warning no longer appears.
