### ISSUE TITLE
National Moderators List

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#19]
New section in front-end which shows the profiles. Various changes in the backend to use existing data when possible and add/change additional data by admins (for example photo upload).
It should not be a duplicate of Google Drive or a photo editing app. 
-The images can be uploaded after the user(admin) has resized them on their own device.
-The uploaded photo's have an 1 to 1 relation with a user account.

**Comment by patrickakk** [comment]
The development of this feature is finished.
Open: Persistent file storage is expected to be implemented soon.

Public list: https://test-dhcr.clarin-dariah.eu/info#national-moderators
Edit user to enable and upload photo (click edit): https://test-dhcr.clarin-dariah.eu/users/moderators

@PixlTracer Do you have time available to test this feature? 
Please note:  All changes and files uploads need to be done again in production, so I would recommend only to test a few and make the permanent changes when the feature is released.

Questions:

- The display of the email address is currently exactly implemented as requested (on the screenshot). This  might not look so nice. Are there other suggestions?

- At the contact section https://test-dhcr.clarin-dariah.eu/info#contact

there is also a list with moderators. This might be redundant? What should be done with that?

**Comment by patrickakk** [comment]
Please note that the content of the about field will be displayed public if you check the box.!

Please read the explanations at the edit user page.

**Comment by PixlTracer** [comment]
hi Patrick, 
it is on my to do list, I'll look into the feature and get back to you.

**Comment by PixlTracer** [comment]
a) I tested this feature, but I could not upload a (resized) picture (170x132px)
- max. MB for photo uploads?
- which photo file format (.png, .jpeg, etc.) should be used? or: various formats?

b) I checked "Show this user in the National Moderators List" - the email displayed is "name dot surname (at) fcsh dot unl dot pt" -- is the 'dot' on purpose? 
name.surname(at)fcsh.unl.pt would be a (desired) alternative solution 

c) "At the contact section https://test-dhcr.clarin-dariah.eu/info#contact there is also a list with moderators. This might be redundant? What should be done with that?"
- Exactly. The Natio
"The DHCR maintains a system of national moderators, who review newly entered courses, help with registration issues and are encouraged to disseminate the DHCR initiative among institutions of their countries. Below you can find an overview of

**Comment by PixlTracer** [comment]
a) I tested this feature, but I could not upload a (resized) picture (170x132px)
--> max. MB for photo uploads?
--> which photo file format (.png, .jpeg, etc.) should be used? or: various formats?

> The uploaded photo's have an 1 to 1 relation with a user account.

what do you mean with '1 to 1 relation with a user account'?

b) I checked "Show this user in the National Moderators List" - the email displayed is "name dot surname (at) fcsh dot unl dot pt" -- this is my bad, I expressed this in a wrong way in my profiles template suggestion; could this be amended to:
name.surname(at)fcsh.unl.pt?

c) 

> At the contact section https://test-dhcr.clarin-dariah.eu/info#contact there is also a list with moderators. This might be redundant? What should be done with that? 

-- Exactly! 
The intention of requesting this feature in the first place was to 'pimp' this very section with the profiles of the NM; hence, the section 'Contact us' can be subsituted with this new feature -- and could be re-named to:
National Moderators - Contact us 
"The DHCR maintains a system of national moderators, who review newly entered courses, help with registration issues and are encouraged to disseminate the DHCR initiative among institutions of their countries."
Please add "Below you can find an overview of moderated countries and their respective moderators. In case you have questions do not hesitate to drop a line:"

d) last but not least: considering the implementation of this feature, is it still possible to keep the contact form/bug report (https://test-dhcr.clarin-dariah.eu/info#contact)? We should definitely offer a way for bug reporting to both user groups, with and without login.

**Comment by patrickakk** [comment]
Update: Persistent file storage is implemented (by Dalibor).

@PixlTracer:
a) 
The filetypes png, jpg and jpeg are accepted. Do you need additional formats? There is no filesize limit (in MB) for the file, but with a maximum size of 170x132px this will usually be < 1MB.

What did not work when uploading a picture? Which (error) message was shown in the top right corner?

Can you send me the picture per mail, so I can test it as well? (Maybe not attach it here for privacy reasons).

> what do you mean with '1 to 1 relation with a user account'?

One photo can only be attached to one user account. One user account can only have one (or zero) photo's.

b) 
Change implemented. This will probably be visible tomorrow.

c)
> and could be re-named to: National Moderators - Contact us

I've renamed to current "Contact Us" section to "Contact Us (old)", so that we can find a place for the remaining content. The national moderators have been removed here now, since they are in the new section.

About the change of the title to: "National Moderators - Contact us":
This is a very long text. I've changed this in the "accordeon" at the info page, but not in the menu. Can you check the amount of characters of other menu items and suggest a shorter text?

At "Contact Us (old)" we now have some remaining items:
-Administrators
-Contact Form
-Bug Report (which also needs to be updated, but that might be a seperate feature request)

What do we want to do with those 3 items?

d) What do you suggest?


@IvdL22: 
Do you also want to review this feature or can we release it as soon as Anna has finished her review?

**Comment by patrickakk** [comment]
Update:
Currently the persistent file storage doesn't work. Which means the photo's are removed, as soon as new code is deployed. This is work in progress.

In the meantime we still can test and adapt all other things, as explained above. And file upload should work anyway.

**Comment by PixlTracer** [comment]
ad a) Picture Upload Mystery RESOLVED:
the pic needs to be 132x170px (and not 170x132px) - I confused the measurements (sorry for that!!)

Additionally, I created a test entry in the about section (the description field), when I hit 'update user', the changes (i.e. the test description) were implemented (yay!).
on a side note: when reviewing my test entry at https://test-dhcr.clarin-dariah.eu/info#national-moderators I noticed a small box in the bottom right corner (screenshot also attached) that contains an error message for the website holder in red letters (in German language) - I guess this can be ignored, since we try out all of this stuff in the test instance?

![error message (bottom right corner) on test instance](https://user-images.githubusercontent.com/117655705/203826783-47240789-253c-4230-b9f2-37181c34bf91.png)


ad b) works, thank you!!

ad c) Suggestion: 
- We could name the new section simply 'National Moderators'

- Then we could remove the contact form from the 'contact us (old)' section, because we have the NM's (and their email addresses respectively) displayed above;
if we keep the 'Admin' (incl. display of email address) + 'Bug Report' in the 'contact us (old)' section (https://test-dhcr.clarin-dariah.eu/info#contact) 
we could simply re-name it to: Admin & Bug Report 

@IvdL22 what do you think, does a better name for the sections come to your mind?

**Comment by PixlTracer** [comment]
ad a) 
Picture Upload Mystery RESOLVED:
the pic needs to be 132x170px (and not 170x132px) - I confused the measurements (sorry for that!!)

**Comment by patrickakk** [comment]
a)
> when reviewing my test entry at https://test-dhcr.clarin-dariah.eu/info#national-moderators I noticed a small box in the bottom right corner (screenshot also attached) that contains an error message for the website holder in red letters (in German language)

Thanks for looking closely.
This is an error from the Google Recaptcha which is attached to the contact form. It works without problems in dev and prod. I suppose that the test instance (which was created later) is not on the list of "allowed domains". Until now, I ignored this, since we have a huge amount of other tasks in the backlog. Feel free to create a new issue for this if needed ;)

c)
-renamed to "National Moderators"
-contact form removed
-renamed to "Admin & Bug Report"

Questions:
1. Do we want to add something like: "For not moderated countries, please contact the administrators (listed below). " to the Moderators section?

2. How should somebody who is not familair with the structure of moderators/admin be able to find an easy way to contact us, if we remove the word "contact"?

3. The way in which the emailadress / link is displayed, is inconsistent between moderators and admins?

4. Would this be the right moment to decide what to do with the bug report item? (This was a separate topic). The current link points to a repo with is not even used, since mai 2022. We could replace this by a contact form, which sends an email to all (three) administrators when a bug is reported?

**Comment by PixlTracer** [comment]
dear Patrick, 
thank you for both a) & c)!

ad 1.: absolutely! great suggestion, please keep the text

ad 2.: good point. how about: "Contact: Admin & Bug Report"?

ad 3.: could we create then 'admin profiles' alternatively? like, use the NM as template but use it for the admins; or: do you think it is sufficient, to keep it the way it is, i.e. the email address is shown when hovering over the admin's names?

ad 4.: yes, this would be a possible workaround. 
once we receive an email about a bug, a bug issue needs to be created on Git 
-- who is the one in charge then, who will create the bug issue? @patrickakk would you take on this duty?
(in case we don't assign someone from the team, we risk that a bug that has been reported does not end up documented on Git)

**Comment by IvdL22** [comment]
Dear both,
a) I am not sure about "Contact: Admin & Bug Report".  In general, there is a clear distinction between Contact (to ask general questions about DHCR) and Technical Support (bug reporting). We could have two separate buttons: 

1) Contact (contact admins)
2) Technical support (contact details of Patrick). 

Add a line at the bottom: ''Before you contact us, please check the FAQ page to see if your enquiry has already been answered."'

In order not to confuse the users, I will add specific contact info for the national moderators directly in their dashboards.

**Comment by patrickakk** [comment]
> ad 1.: absolutely! great suggestion, please keep the text

I've added the text. (To the moderators section, it was already at the administrators section).

> ad 2.: good point. how about: "Contact: Admin & Bug Report"?

Changed in menu and page.

> ad 3.: could we create then 'admin profiles' alternatively? like, use the NM as template but use it for the admins; or: do you think it is sufficient, to keep it the way it is, i.e. the email address is shown when hovering over the admin's names?`

Yes, this might be possible. I'll get back on this later.

> ad 4.: yes, this would be a possible workaround.
> once we receive an email about a bug, a bug issue needs to be created on Git
> -- who is the one in charge then, who will create the bug issue? @patrickakk would you take on this duty?
> (in case we don't assign someone from the team, we risk that a bug that has been reported does not end up documented on Git)

Only as a workaround? What would be the desired final solution?

In case of the contact form, my proposal would be: the bug reported by the user get send to all admins which are showed. The responsibility to process the mail and create an issue if required could be for the developer. To create transparency the others are informed as well, so that nothing "get's lost"  ;)

**Comment by patrickakk** [comment]
> In general, there is a clear distinction between Contact (to ask general questions about DHCR) and Technical Support (bug reporting). We could have two separate buttons:

There are 2 sections, found here ?
https://test-dhcr.clarin-dariah.eu/info#contact

> Add a line at the bottom: ''Before you contact us, please check the FAQ page to see if your enquiry has already been answered."'

The line has been added.

> In order not to confuse the users, I will add specific contact info for the national moderators directly in their dashboards.

Can you explain what should be done and why?

**Comment by IvdL22** [comment]
1. **Contact: Admin & Bug Report** -> this does not look very elegant, I would keep it simple: **Contact**. I also think that it should be put at the bottom of the list. (We actually need to restructure the whole page)

Immediately, under **Contact**, place the text -> _Before you contact us, please check the [FAQ page](https://test-dhcr.clarin-dariah.eu/faq/public) to see if your inquiry has already been answered._ 

2. **Administrators**
For general questions regarding the use of the DHCR platform and related dissemination activities, please contact either Anna Woldrich or Iulianna van der Lek. _(Could we maybe have just one general email address here and not our personal ones in order to avoid getting spammed)_

For technical questions and support, please contact Patrick Akkermans, the technical co-chair of the working group.

3. **Bug report**
Can a user file a bug report if he or she does not have log in details to github?

**Comment by patrickakk** [comment]
> ad 3.: could we create then 'admin profiles' alternatively?

@PixlTracer:
They are created and you can check them out here:
https://test-dhcr.clarin-dariah.eu/info#contact

A user is listed there automatically if "show as admin on contact page" is checked. You can add photo's in the same way as for moderators, but now you have to use "All Users".

**Comment by patrickakk** [comment]
Update: The persistent file storage should be working in all instances now. This means you can upload photo's and they will stay in the container, even if now code is deployed. As well there is a backup for the files which are uploaded in the prod instance.

Thanks to Dalibor for this great solution.

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 :

The topic of this issue is National Moderators List. For the remaining items on the info page, I would suggest that we choose now for a minimal acceptable level and discuss the "perfect solution" later 
(As discussed today in the JFX) , in: https://github.com/acdh-oeaw/dhcr-main/issues/23


I've made the following changes:
-Changed title to "Contact Us"
-Hidden new admin profiles
-Restored old admin list

This way we should have everything in place and ready to release?

TODO:
Could you please check if the National Moderators List are implemented as requested?  If yes, please add the label "Done" and remove the label "InReview".

Then I can release the next version. This will be 2022-11/2 which also includes hiding the broken filter buttons.

Thanks for your cooperation.

**Comment by IvdL22** [comment]
> 

@patrickakk Would it be possible to replace the current text with the one below if @PixlTracer does not have any further suggestions?

_The course entries in the DH registry are moderated by a group of national moderators who review and approve newly entered courses, provide assistance with registration issues and disseminate the DHCR activities among the institutions of their countries. 

In case there is no moderator listed for your country, please contact one of the administrators (add link) if you have any questions._

**On Maria's contact card, please improve the text as follows:**
As a national coordinator of the Greek CLARIN:EL network (www.clarin.gr), I am moderating the DH activities offered by the Greek universities.

Thank you.

**Comment by patrickakk** [comment]
> Would it be possible to replace the current text with the one below

Yes. @PixlTracer: Can you confirm the text?

> On Maria's contact card, please improve the text as follows

That wouldn't make sense now. This text is based on the field "About" from the user profile. The test instance has it's own database, so changing it here won't change this in production.

When the feature goes into production you could change it yourself, by going to: Dashboard / Contributor Network / Moderators and click on edit. Or you could ask Anna, since she might be adding all the photo's anyway ;)

You can also try it now yourself and the changes are instantly visible in the test instance.

**Comment by PixlTracer** [comment]
I will take care of implementation of Maria's Text, 
I agree with everything and will change the status label to done.

**Comment by patrickakk** [comment]
> @patrickakk Would it be possible to replace the current text with the one below if @PixlTracer does not have any further suggestions?

> _The course entries in the DH registry are moderated by a group of national moderators who review and approve newly entered courses, provide assistance with registration issues and disseminate the DHCR activities among the institutions of their countries.
> 
> In case there is no moderator listed for your country, please contact one of the administrators (add link) if you have any questions._

The text has been replaced.

**Comment by patrickakk** [comment]
This feature is finished and available in 2022-11/2.

**Comment by patrickakk** [comment]
Reported by Anna:

>  I have tried to update Walter Scholger's Profile 
-- When clicking on 'Show in Mods List' I get an error message (screenshot attached) and the entry is not shown in the registry.

(https://dhcr.clarin-dariah.eu/info#national-moderators)

**Comment by patrickakk** [comment]
Reported by Anna:

> please ignore point 2) - I was able to resolve the issue;
> however, there seems to be a glitch at https://dhcr.clarin-dariah.eu/info#national-moderators
> --> screenshot attached
![Bildschirmfoto 2022-12-06 um 16 51 54](https://user-images.githubusercontent.com/97846194/205968680-39fcd27d-ae87-4b45-82ed-2134d4613be7.png)

**Comment by patrickakk** [comment]
@PixlTracer:

> I was able to resolve the issue

Did you "solve" the issue, by selecting a placeholder for the photo, instead of not uploading a photo?

Thanks for the workaround, but of course this should not be necessary. For some reason in the test instance it worked fine to "add" a moderator without uploading a photo, but in production it results in an error. I found the cause and will be working on a solution.

>  there seems to be a glitch

It seems to be related to the "length" of the content. (There is quite some content). Would it be fine to move the national moderator list to a separate page?
The menu entry will remain the same but it will then be moved from the info page to a separate page, without "accordeons".
This might be a quick solution. How about that?

Maybe we want to communicate it first after this is solved?  ;)

**Comment by patrickakk** [comment]
@PixlTracer:

A fix for "no fileupload" is implemented.

As well: The separate page for the Moderators List has been implemented and can be found here:
https://test-dhcr.clarin-dariah.eu/national-moderators

It also provides a nice short url ;)

It's available trough the menu and here:
https://test-dhcr.clarin-dariah.eu/info#national-moderators

I've enabled all moderators for the list in test, and everything seems to be working fine?

Can you check it and then change the label to done?
Then I'll release the fixes.

**Comment by PixlTracer** [comment]
@patrickakk wonderful solution, thank you!

**Comment by patrickakk** [comment]
Implemented in 2022-11/3
