### ISSUE TITLE
Implement unique for institution name

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#26]

**Comment by patrickakk** [comment]
Implemented in 2022-12.

It can be reviewed here: https://dev-dhcr.clarin-dariah.eu/institutions/add

See the screenshot for the validation message.

![duplicate_institution_validation_message](https://user-images.githubusercontent.com/97846194/207384461-1d853ca6-24b9-4bec-b26f-a4d718f14f52.png)

**Comment by IvdL22** [comment]
@patrickakk It looks good, thank you.

**Comment by PixlTracer** [comment]
@patrickakk thank you! changed the label to done

**Comment by patrickakk** [comment]
Implemented in 2022-12
