### ISSUE TITLE
Change MAP api keys

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#28]
There are ACDH keys available.

This is for Mapbox.

**Comment by patrickakk** [comment]
@vronk where can I get the keys?

**Comment by patrickakk** [comment]
new key is available

**Comment by patrickakk** [comment]
The new generic API key works. It works for the maps in the login area at Courses Add/Edit. It doesn't work for the map on the main page.

First Leatlet needs to be on the latest version, see separate issue.

**Comment by patrickakk** [comment]
In the meeting of today we agreed to remove it from the milestone. This task is waiting for issue https://github.com/acdh-oeaw/dhcr-main/issues/66 to be completed and that takes some time, And currently doesn't have the highest priority.

**Comment by patrickakk** [comment]
It seems that changing the Mapbox API didn't work in the beginning, because there was a custom style used, which was linked to the old key.

Now I've migrated to a default Mapbox style. The style looks nice and I didn't see any unpleasant differences.
As well the new mapbox api key is used in dev and test.

**Comment by patrickakk** [comment]
`Note to myself: Change global key when this goes into production and remove 2x env key`

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 

Can you review this?

You could check that the map still works and if you're satisfied with the slightly changed style/design of the map:

https://test-dhcr.clarin-dariah.eu/

**Comment by IvdL22** [comment]
@patrickakk The map seems to work fine. I like the design as well, thank you :)

**Comment by patrickakk** [comment]
Implemented in 2023-09.

`After this goes into production, global keys need to be changed, see above`

@IvdL22 I've changed the label to "done" for you ;)

**Comment by patrickakk** [comment]
repository secret updated to new map api key.
env secrets removed.
all containers redeployed after changes.
everything works fine.
