### ISSUE TITLE
Change Recapcha keys

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#29]
This is for Google Re captcha.

**Comment by patrickakk** [comment]
@vronk where can I get the keys?

**Comment by vronk** [comment]
@patrickakk is this connected to a google account?
How does one get such a key?

**Comment by patrickakk** [comment]
@vronk 
https://developers.google.com/recaptcha/intro

> To start using reCAPTCHA, you need to [sign up for an API key pair](http://www.google.com/recaptcha/admin) for your site.

Yes, it looks like it's connected to a Google account.

and

> First, choose the [type of reCAPTCHA](https://developers.google.com/recaptcha/docs/versions) and then fill in authorized domains or [package names.](https://developer.android.com/guide/topics/manifest/manifest-element.html#package) After you have accepted the terms of service, click Register to get new API key pair.

Currently the reCAPTCHA is used on our registration form, here: https://dhcr.clarin-dariah.eu/users/register

It looks like it's the following version: 
reCAPTCHA v2 (Invisible reCAPTCHA badge)

and

maybe the url's for the test and dev instance could also be added, so that it also works there?

**Comment by vronk** [comment]
@dpancic, could you, please, generate reCAPTCHA key under acdh-google account for dhcr?

**Comment by patrickakk** [comment]
keys are available

**Comment by patrickakk** [comment]
second key is missing. waiting for answer

**Comment by patrickakk** [comment]
Moved to Mai milestone, to give a realistic estimation of implementation.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

The new Google Recapcha keys are implemented. You can check this by visiting the registration form in the test instance (it didn't work before there):
https://test-dhcr.clarin-dariah.eu/users/register

Or checking the same page in production and see that it still works ;)
https://dhcr.clarin-dariah.eu/users/register

In the bottom right corner, you can see:
![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/079fdb4f-c435-4b86-a571-294b78e29961)


Can you review this and change the label to Done?

**Comment by IvdL22** [comment]
@patrickakk I Checked, all good! Many thanks!

**Comment by patrickakk** [comment]
Implemented immediately. Noticed in release notes of 2023-05.
