### ISSUE TITLE
increase size of checkboxes

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#37]
at edit courses. checkboxes: online course, show course in registry

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer
As requested a while ago, the size has been increased ;) Can you review this?

This applies to all check boxes, everywhere in the application, for example both add and edit course pages and the registration form.

Examples:
- https://dev-dhcr.clarin-dariah.eu/users/register
- https://dev-dhcr.clarin-dariah.eu/courses/add

Can you change the label to Done if satisfied?

**Comment by IvdL22** [comment]
@patrickakk Looks good, thank you!

**Comment by patrickakk** [comment]
Implemented in 2023-05.
