### ISSUE TITLE
 Update readme.md content and remove ops text

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#40]

**Comment by vronk** [comment]
We could also just remove the old content.
don'T really have to explain the installation. DHCR is not meant to have many instances running. 
Just state this is the code for DCHR and point to the official instance.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

Can you review this?

The updated file can be found here:
https://github.com/acdh-oeaw/dhcr-main/blob/dev/README.md

Can you change the label to Done if satisfied?

**Comment by IvdL22** [comment]
@patrickakk It looks good to me, thanks!

**Comment by patrickakk** [comment]
Implemented in 2023-12
