### ISSUE TITLE
New bug reporting process

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#41]
On Github?

**Comment by patrickakk** [comment]
Bug because the current button links to the old repo.

We talked about this in a meeting that there should be a link to "create issue" on GitHub on the repo dhcr-main.

So the new process will be that normal users have to create a GitHub issue.

The change of the link is also addressed here; https://github.com/acdh-oeaw/dhcr-main/issues/42#issuecomment-1465211487

Moved to mar23 milestone, since this work can be done together.

**Comment by patrickakk** [comment]
The possibility to create an issue on Github is (currently) only available after login to Github.

And same problem for API v2 and v1 as well. The links there (to issue tracker) should also be updated.

**Comment by patrickakk** [comment]
waiting for decision in meeting

**Comment by patrickakk** [comment]
Moved to Mai milestone to have a realistic estimation of when this will be implemented.

**Comment by PixlTracer** [comment]
in case a user reports a bug, we can assume that he/she has a github account and makes use of github to report.
--> implement a link to DHCR github repo - where the user can write down the bug
alternative solution: implement 'bug-report' form on website - the message will be sent to [dhcr-helpdesk@clarin-dariah.eu]

we can discuss this in the next tech meeting

**Comment by patrickakk** [comment]
Talked about in the meeting today:

The link on the button "report bug" will be updated to create an issue in this repo.  https://github.com/acdh-oeaw/dhcr-main/issues/new 

Explanation line will be added that users need to create a GitHub account, etc.

@vronk Can you add the explanation you've suggested here?

**Comment by patrickakk** [comment]
Blocked: Waiting for text that should be added as explanation

**Comment by patrickakk** [comment]
The explanation text as agreed on in the meeting:

“Please use your GitHub account in order to file a bug report. In case you haven't created one, please create an account here (link). Alternatively, you can contact us via dhcr-helpdesk /at/ clarin-dariah.eu.”

**Comment by patrickakk** [comment]
Changed description to match the process:

" Click the button below to create a new issue and file a bug report. You'll need a GitHub account to do this. In case you don't have a GitHub account, you can create one. Alternatively, you can contact us via dhcr-helpdesk /at/ clarin-dariah.eu. " 

Development finished.
Implemented in 2023-05.

Currently blocked. This can be reviewed when 2023-04 is released.

**Comment by patrickakk** [comment]
The result is visible here:

- https://dev-dhcr.clarin-dariah.eu/info#contact
- https://dev-dhcr.clarin-dariah.eu/api/v1/
- https://dev-dhcr.clarin-dariah.eu/api/v2/

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer  Can you review this?

You can use the links from the dev instance above.

**Comment by IvdL22** [comment]
@patrickakk Suggestion for the text:

Click the button below to create a bug report on GitHub. In case you don't have a GitHub account, you can create one [here](https://github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home). Alternatively, you can contact us via dhcr-helpdesk /at/ clarin-dariah.eu.

No need to wait for Anna.

**Comment by patrickakk** [comment]
@IvdL22 The text has been updated, see https://dev-dhcr.clarin-dariah.eu/info#contact

Implemented in 2023-05.
