### ISSUE TITLE
Review access rights for google drive folders

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#43]

**Comment by patrickakk** [comment]
Public part:
https://drive.google.com/drive/folders/1i6j4ZixkOdXyEupDT6IIZR9yzsDkXQo5

For WG only:
-please ask link per mail-

**Comment by PixlTracer** [comment]
@IvdL22 you mentioned something about including the 'official public' DHCR drive for national moderators into the CLARIN drive? is this still a thing?
the WG drive can stay private, no action needs to be taken?
thanks for your feedback!

**Comment by IvdL22** [comment]
@patrickakk @PixlTracer I do not remember saying that the DHCR drive will be moved to CLARIN. We are actually requested to move it to the DARIAH WG drive, but we are waiting for more instructions from the DARIAG WG Coordinator. We can put this task on hold until further notice. @PixlTracer Please correct me if I am wrong.

**Comment by PixlTracer** [comment]
dear @IvdL22 thanks for clarification, I thought it was CLARIN but obviously the drive in question refers to DARIAH. sorry for the confusion!

**Comment by patrickakk** [comment]
@PixlTracer @IvdL22 

Do you have an update on this?

**Comment by IvdL22** [comment]
@patrickakk @PixlTracer  We received instructions on how to move the DHCR WG folders to the DARIAH shared Google Drive: https://docs.google.com/document/d/1BgbLf-67CTdOHX14joUopdHdnVPMvigIuYqfxf0QdMs/edit?usp=sharing. I have not done anything yet. @PixlTracer Let's try to look at the instructions together and move the folders before the summer holidays.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 
Thanks for the update. I've changed the label to Todo and moved the issue to the July milestone. Is that a realistic representation of the situation?
Feel free to change if you think otherwise.

**Comment by PixlTracer** [comment]
I agree with @IvdL22 we can move it after DARIAH AE;

**Comment by PixlTracer** [comment]
Since the migration process did not work as planned, I made a local copy of the internal/external folders and uploaded them;
Both folders are now available [here in the DARIAH drive](https://drive.google.com/drive/folders/1vmOsMUJTo98DrrFdj8M5jN2tByKYPdQn):
I've marked the original folders with [deprecated]; ([here](https://drive.google.com/drive/folders/1gJvl5IRkl84bkTAVnqvHTFTtBK04zBwn)/[here](https://drive.google.com/drive/folders/1i6j4ZixkOdXyEupDT6IIZR9yzsDkXQo5))

**Comment by patrickakk** [comment]
@PixlTracer 

Could you explain the purpose of making the copy?

@IvdL22 @PixlTracer 
Do we all agree on the initial purpose of this issue? (Maybe it wasn't specified clear enough)

> The files on the internal Google drives are accessible by everybody, without authentication (login) 

When looking at the last comment of PixlTracer , the link to DARIAH drive is still accessible to everyone?

Dariah drive link:
https://drive.google.com/drive/folders/1ZHh5pR2eDtBTBG2z_7Orz_XpXV8gkzrS

A folder on Dariah drive marked as internal:
https://drive.google.com/drive/folders/1ZHh5pR2eDtBTBG2z_7Orz_XpXV8gkzrS

You could check this by opening the link  "In new private Window", if your browser supports this?

Do we need to take additional action to make sure that folders marked as internal, are really only available internally?

Edit/added:
Is everybody aware that the files in internal folders also contain privacy related information, like email addresses, etc. ? Maybe it would be a good idea to be more careful with those?

**Comment by IvdL22** [comment]
@patrickakk I do not fully understand the technical issues when @PixlTracer tried to move the folders from OEAW drive to the DARIAH GDrive. Anna, could you clarify, and we can try to find a solution together?

@patrickakk, the chairs folder should, indeed, be accessible only to the chairs and guests. Sometimes, we need to collaborate on files for joint abstracts with other colleagues.

**Comment by vronk** [comment]
The permission level has been restricted to selected persons.
Ask Matej if you need access for yourself or anybody.

**Comment by vronk** [comment]
@IvdL22, @PixlTracer  we need a discussion on who has access to the gdrive.
