### ISSUE TITLE
Improve handling of multi-select (disciplines, techniques, objects) in course form

### ISSUE THREAD

**Issue by vronk** [acdh-oeaw/dhcr-main#46]
In the add/edit course form, 
allow more comfortable selection of multiple items in the disciples/tadiran techniques/tadirah objects fields 
(without the need to press a key, perhaps via a tickbox or similar)

**Comment by PixlTracer** [comment]
suggestion:
when using the filters at https://dhcr.clarin-dariah.eu/ a user can easily select more than one country by simply clicking on the respective country; (see screenshot below) 

![DHCR Filter Options country](https://github.com/acdh-oeaw/dhcr-main/assets/117655705/0cfcb3c1-bb9d-4e2e-8acd-1768e38851ed)

when navigating to entering a new course at https://dhcr.clarin-dariah.eu/courses/add the section below the map could be structured in a similar way like in the screenshot above:
choose discipline --> drop down
choose technique --> drop down
choose object --> drop down 
the contributor can then easily select the suitable variables; in case there has been a mistake in checking a wrong item, it can be easily removed by clicking the (x) -- same workflow like in the screenshot above

**Comment by vronk** [comment]
convenience improvement - dropped due to capacity shortage.
