### ISSUE TITLE
A way to see what users are searching for

### ISSUE THREAD

**Issue by vronk** [acdh-oeaw/dhcr-main#49]
To implement in the application may be rather time-consuming.

But logging via matomo should allow poor man's view on this.

**Comment by patrickakk** [comment]
Need to talk about this in one of the next meetings to discuss the details.

**Comment by patrickakk** [comment]
Blocked until a meeting in June where Iulliana is present.

**Comment by patrickakk** [comment]
Information in Matomo is sufficient at the moment.
