### ISSUE TITLE
Production instance behaves different than test instance

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#52]
A new feature was reviewed in the test instance and worked fine. When the feature was released into production an error occurred. This should have been the case in the test instance as well.

(The bug in the new feature has been solved).

In January, Omar and I will take a look into this, why both instances behave different.

**Comment by dpancic** [comment]
`A new feature was reviewed in the test instance and worked fine. When the feature was released into production, an error occurred. This should have been the case in the test instance as well.
`
Which error is returned?

**Comment by patrickakk** [comment]
@dpancic: An error from the php framework, CakePHP: "An Internal Error Has Occurred". This happened in production. It did not happen in the test instance, but it should have happened there as well.

It looks like the application is in debug mode in the test instance, although the variable is set to false. This is the result from rancher shell from the test instance:

> printenv | grep 'DEBUG=' 
> DEBUG=false

It looks like the variable has the correct value.

1. Can you tell why the test instance behaves different?
2. When this is fixed, can we do the same for the dev instance?

**Comment by dpancic** [comment]
@patrickakk K8S_SECRET_DEBUG env variable is set to false in Github secrets as repo variable, and is also forwarded to the container correctly after deployment, but the app is not using it.
That usually happens when we hard-code a variable somewhere in the app, for example here https://github.com/acdh-oeaw/dhcr-main/blob/test/config/app.php on lines 24-33

```
 /**
     * Debug Level:
     *
     * Production Mode:
     * false: No error messages, errors, or warnings shown.
     *
     * Development Mode:
     * true: Errors and warnings shown.
     */
    'debug' => filter_var(env('DEBUG', true), FILTER_VALIDATE_BOOLEAN),

```
The app should be configured to check if env variable is set (already present) and if not to use some default value from the config/app.php

**Comment by patrickakk** [comment]
@dpancic  Thanks for your help.

Today I've added some code to generate on purpose an "Internal Error". This works exact the way it's supposed to be in the test instance. And that confirmes the app is *not* running in debug mode, exact the way it's supposed to be. For some reason we didn't get this error in December. Maybe insufficient/wrong testing?

It looks like everything works fine in the test instance and in the dev instance. Both are not running in debug mode. That is good.

I'll close the issue.

Btw: the variable debug is not hard coded here?
`debug' => filter_var(env('DEBUG', true), FILTER_VALIDATE_BOOLEAN),`

> The second value passed to the env function is the default value. This value will be used if no environment variable exists for the given key.

The first value 'DEBUG' is the name of the key to look for in the system environment.
