### ISSUE TITLE
upgrade to php 8.1

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#53]
php 7.4 is eol

**Comment by patrickakk** [comment]
Implemented in 2023-02

**Comment by patrickakk** [comment]
This also includes:

- [x] Migrating the main application to the latest version of the framework
- [x] Migrating API v2 to the latest version of the framework
- [x] Migrating API v1 to the latest version of the framework

Especially the last task requires a lot of time, because this part has not been updated for a long time.

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 
cc @vronk 
Al tough this issue started with only a short sentence, it  was a lot of work and has impact on every single part of the application (every mouse click). So it's not possible to provide a specific link to an url for review. It affects all pages (incl. login) under:
https://test-dhcr.clarin-dariah.eu/
https://test-dhcr.clarin-dariah.eu/api/v1/
https://test-dhcr.clarin-dariah.eu/api/v2/

and as well all API calls which are only specified in the documentation and not on the API landing page.

The API v1 was running on an ancient version of the Framework, which was probably more than 4 years old.

For API v1 and API v2 as well as the main application [dhcr-main], the following improvements have been made:

- Migration to the latest version of the framework
- Migration to PHP 8.1
- Refactoring of all code which needed to be changed
- This includes also refactoring the routing of all three parts, which has impact on every mouse-click within the application

What should be the visible result? Preferably nothing, since that means that everything works as before in the way it's supposed to.  ;)
The new versions which are used, are visible at "App Info", here:
https://test-dhcr.clarin-dariah.eu/statistics/app-info

Have fun with the review :-P

Please change the label to Done and write a line if you're satisfied.

**Comment by vronk** [comment]
Looked at the API endpoints for v1 and v2 and did not find anything suspicious.
Everything seems to work smoothly.
Green light from my side.

**Comment by IvdL22** [comment]
@patrickakk 
The website seems to work fine.

I also clicked through the API2 page. Noticed that this link https://app.swaggerhub.com/apis-docs/hashmich/DHCR-API/1.2 took a bit of time to load.

Green light from me as well, thank you for all the work!

**Comment by patrickakk** [comment]
@IvdL22  Thanks for the notification. As info: Swaggerhub is an external part, which is hosted somewhere else.

**Comment by patrickakk** [comment]
Implemented in 2023-02
