### ISSUE TITLE
implement notification mail for moderators when a new course is added

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#54]
moderators don't get a mail with approval request when a new course is added

**Comment by patrickakk** [comment]
Implemented in 2023-02

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 

As talked about in the meeting today, below you can find an anonymized example of a mail which is sent to the moderator when a new course is added.

Can you please review the text below and change the label to done if you both agree on the new text?
They I'll update it in the application.

Note: Text between -- is anonymized or removed

To: --email address of mod/admin--
Cc: --our cc email address--

Subject: [DH Course Registry] New Course waiting for approval

Body text:

Hello Admin,

a new course has been entered in the DHCR and is waiting for approval!

Course Overview
• Course Name: ----
• Education Type: ----
• Institution: ----

Click here to go to "Course Approval", check the details and approve the course:
https://dhcr.clarin-dariah.eu/courses/approve/

--
The Digital Humanities Course Registry: 
https://dhcr.clarin-dariah.eu/

**Comment by IvdL22** [comment]
@patrickakk @PixlTracer 
Looks good! Please capitalise ''a new course'' -> ''A new course...''

I will mark this as done.

Thanks,
Iulianna

**Comment by patrickakk** [comment]
Done.

**Comment by patrickakk** [comment]
Implemented in 2023-02
