### ISSUE TITLE
replace list of admins by one emailaddress

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#56]
currently at "contact us", here: https://dhcr.clarin-dariah.eu/info#contact  all the admins are listed with their own email addresses. This should be replaced by one team mailbox(imap).

The suggested email address is helpdesk@dhcr.clarin-dariah.eu 

This issue is related to https://github.com/acdh-oeaw/dhcr-main/issues/42

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 

Open questions / tasks on this topic:

- [x] 1. Define the exact email address
- [x] 2. Define the purpose
- [x] 3. Define who is going to maintain this
- [x] 4. Define which folder structure we need (inbox, answered mails, pending items, etc?)
- [x] 5. Define how it should be clear for other team members what the status of mails is?

Add task 1:
Did you notice the difference between the CC email address (here https://github.com/acdh-oeaw/dhcr-main/issues/42) and the url of the application?
The CC email address is: dhcr /at/ clarin-dariah.eu
The url of the application is: https://dhcr.clarin-dariah.eu/

This means the email address is not attached to the subdomain where the application is, but at the main domain?

Did you visit that domain before? It available here: https://clarin-dariah.eu/
This is a landing page for all projects which are a cooperation between CLARIN and DARIAH. (Currently there is one, which is the DHCR?)

If we are going to use the main domain (clarin-dariah.eu) I would recommend also to use the text "dhcr" in the email address, so it's clear to everyone that's only about this project.
A possible suggestion could be: dhcr-helpdesk /at/ clarin-dariah.eu ? 
What do you think about that? Are there any other suggestions?

Add task 2:
Herby I copied and modified the definition from here: https://github.com/acdh-oeaw/dhcr-main/issues/42#issuecomment-1427697130

Purpose of the email address: Contact email address for the users to reach out to the DHCR team.

Do we need to add or change something?

Add task 3 & 4 & 5:
Any suggestions?


Edited at 2023-02-13 14:24 by patrickakk  -  Purpose/change: added task 4 & 5

**Comment by vronk** [comment]
decision for email-address: dhcr-helpdesk@clarin-dariah.eu
Patrick will communicatea with Dieter.

**Comment by PixlTracer** [comment]
purpose: Contact email address for the users to reach out to the DHCR team.

[dhcr-helpdesk@clarin-dariah.eu](mailto:dhcr-helpdesk@clarin-dariah.eu)  Patrick will contact Dieter. 

(to be set up as an IMAP account, maintained by Iulianna, Anna)

**Comment by vronk** [comment]
4. for now no special structure needed.
5. Emails not replied will be reflag on unread

**Comment by PixlTracer** [comment]
4) currently we don't need this structure;
5) team members: the three/four of us; leave on unread in case we cannot answer/take an action

**Comment by patrickakk** [comment]
Done. This can be reviewed when 2023-02 is released.

Currently blocked.

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer Can you review this?   

Please see also this comment: https://github.com/acdh-oeaw/dhcr-main/issues/42#issuecomment-1497211268

Currently this issue seems to be redundant. Maybe we can collect the comments in the other issue?

Please change the label to Done when you're satisfied.

**Comment by PixlTracer** [comment]
I will get back to this after having received the new IMAP PW

**Comment by patrickakk** [comment]
Implemented in 2023-03. Now waiting for review.

**Comment by PixlTracer** [comment]
I was able to login today @patrickakk 
everything works fine -- i'll asign the label 'done' to this issue
