### ISSUE TITLE
create explanation for lecturer when institution doesn't exist

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#58]
Does a lecturer know what to do when an institution doesn't exist? Do we need to add an explanation?

**Comment by IvdL22** [comment]
''If your institution is not listed, please go to your Dashboard > Category Lists and add the details. " @PixlTracer What do you think of this description?

**Comment by patrickakk** [comment]
@IvdL22  Lecturers can't do that. They have to ask their national moderator or an admin to add a new institution.

**Comment by IvdL22** [comment]
In that case, I propose the following test:

''If your institution is not listed, please contact your national moderator. "' (@patrickakk You will need to insert the link to the moderators list) Thank you. If you agree with this, you can change the status as you seem fit :)

**Comment by patrickakk** [comment]
@PixlTracer What is your opinion?

**Comment by patrickakk** [comment]
@PixlTracer 

REMINDER:

Would it be possible to indicate if changes need to be made to the text? Or can the text be implemented as specified above?

**Comment by PixlTracer** [comment]
the text can be implemented as specified above, thank you.

**Comment by patrickakk** [comment]
Addition to the explanation above:
This is about "Add Course" and can be found here:
https://test-dhcr.clarin-dariah.eu/courses/add

**Comment by patrickakk** [comment]
and will automatically also apply to "Edit Course", for example this course:
https://test-dhcr.clarin-dariah.eu/courses/edit/384

**Comment by patrickakk** [comment]
development finished. 

this can be only be reviewed after the current version (2023-02) is released.

currently blocked

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer Can you review this?

The links to can be found above. 

Please change the label to Done when you're satisfied.

**Comment by patrickakk** [comment]
Implemented in 2023-03
