### ISSUE TITLE
Add search field or typeahead on the main page

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#62]
@IvdL22  @PixlTracer  Here I'm adding the new idea which came up during the meeting today:

On the main page, where the overview of all the courses is listed, a search field or typeahead could be added to make it easier for users to search for a course and improve the user experience.

**Comment by patrickakk** [comment]
### Searchbar 
![230419_searchbar_clean](https://user-images.githubusercontent.com/97846194/233136363-be24743b-e814-4361-ad1f-e53f3e4357fd.png)

### Searchbar with results
![230419_searchbar_with_results](https://user-images.githubusercontent.com/97846194/233136423-527ce0ee-243d-4393-91ad-b062f19d075f.png)

**Comment by PixlTracer** [comment]
yes!! 🥳
looking forward to this feature!!

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 
Can you please fix the name of this course: https://dhcr.clarin-dariah.eu/courses/view/389
(Note: changes should be made in production)

The name contains the character "  which causes the course to be shown on top of search results instead of sorted after other courses, which start with B

Please write a line when it's fixed.

**Comment by IvdL22** [comment]
@IvdL22 I have fixed it but forgot to do it in production. Does that pose a major problem?

**Comment by patrickakk** [comment]
@IvdL22 It doesn't cause a problem. It just means you have to do it again ;) (now in production), because:
- Production is what is shown to the public
- Production DB is leading, which means it's copied from time to time to test and dev and the data there will be overwritten.

Can you write a line here when it's fixed?

**Comment by patrickakk** [comment]
(the course name specified above is fixed)

**Comment by patrickakk** [comment]
The required unique on course name and institution have been implemented.
Development finished.
Implemented in 2023-04.

@IvdL22  @PixlTracer  Can you review this new feature?

Note: Before releasing this version into production, we need to solve all the conflicts in the production database, as addressed here: https://github.com/acdh-oeaw/dhcr-main/issues/59#issuecomment-1538053009

**Comment by IvdL22** [comment]
@patrickakk Tested the feature and it seems fine.

**Comment by patrickakk** [comment]
Waiting for the conflicts of course names to be solved (see above), then this issue can be closed.

**Comment by PixlTracer** [comment]
commented in issue 59; for consistency I am pasting my thought on the search bar here again:

when using the search bar, a user is entering certain keywords - why not output a list (similar to when applying filters) of all the courses that match the keyword? so we don't need to check the course-names for their uniqueness...

very much looking forward to the deployment of the new feature!

**Comment by patrickakk** [comment]
@PixlTracer 

> when using the search bar, a user is entering certain keywords - why not output a list (similar to when applying filters) of all the courses that match the keyword? so we don't need to check the course-names for their uniqueness...

I'm not sure which part of the application you mean. Is it the main page where the new search bar is visible? Here: https://test-dhcr.clarin-dariah.eu/

Currently the you can search in both course name and institution name or a part of it. Can you explain what you mean?

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

All conflicting course names are changed/solved. As well I've added the course type to the searchbar, because there are courses with identical course name and institution name, that only can be distinguished by having the course type added.

The result can be found here:
https://test-dhcr.clarin-dariah.eu/

A nice test case could be to search for "Digital Humanities - Universität Basel", since this didn't work before.

Can you review this and change the label to Done if satisfied?

**Comment by IvdL22** [comment]
@patrickakk It works fine, much appreciated!

**Comment by patrickakk** [comment]
Implemented in 2023-04.
