### ISSUE TITLE
Migrate to PHP 8.2

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#65]
Since 2023-03-30 the application uses PHP 8.1 (in test and dev). This will be in released in version 2023-02.

PHP 8.2 was released in dec-22. 
Some work needs to be done to migrate to this version.

**Comment by patrickakk** [comment]
Fix other deprecation warnings as well

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 

This is a very technical issue, but since we agreed on the workflow to review every issue, before closing, I'll leave it up to you ;)

Can you review this and change the label to Done?

You can visit the dev instance https://dev-dhcr.clarin-dariah.eu/
And check that everything still works and no deprecation warnings are displayed.

**Comment by PixlTracer** [comment]
wonderful, thanks!
I'll set the label 'done'

**Comment by patrickakk** [comment]
Implemented in 2023-08.
