### ISSUE TITLE
Introduce generic email address notation and avoid direct mailto links

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#67]
Currently email addresses are presented in different formats on different parts in the application (mailto link, (at), /at/, plaintext).

In the meeting from today, we agreed on a new generic format for the whole project. This will also include the usage in GitHub comments. This will be:

user /at/ domain.com (please notice the spaces before and after /at/ )

Purpose of this issue:

1. Document this specification
2. Find all the occurrences of email addresses in the application and update to the new format

@PixlTracer @IvdL22 Please read the info above as documentation.

**Comment by patrickakk** [comment]
updated/checked at:

- national moderators
- contact us

not affected: 

- imprint. Since this is shared content, maintained elsewhere.

todo:

- [x] change for course detail page
- [x] update api v1 + v2

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 
What format do we want to use at the course detail page, for example here:
https://test-dhcr.clarin-dariah.eu/courses/view/384
(look at the bottom)

**Comment by PixlTracer** [comment]
is it possible to split the meta data info into 2 parts and avoid a hyperlink / mailto? 
e.g.:
Lecturer: Name, Surname 
contact: user /at/ domain.com

**Comment by patrickakk** [comment]
@PixlTracer Yes

@IvdL22 Do you agree with the format?

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer  Can you review this?

Examples:
- https://test-dhcr.clarin-dariah.eu/national-moderators
- https://test-dhcr.clarin-dariah.eu/info#contact
- https://test-dhcr.clarin-dariah.eu/courses/view/725
- https://test-dhcr.clarin-dariah.eu/api/v1
- https://test-dhcr.clarin-dariah.eu/api/v2/

Btw: The email at both API pages will also be changed to the helpdesk address

**Comment by IvdL22** [comment]
@patrickakk I agree, please proceed. No need to ask Anna.

**Comment by patrickakk** [comment]
Implemented in 2023-04.
