### ISSUE TITLE
Remove social media links and content.js resource

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#68]
This page
https://dhcr.clarin-dariah.eu/pages/news#social-media
contains a list of links posted on social media.
The list is redundant and the file content.js is hosted on some other FTP server. That's not the preferred way, since all resources should be on one location.

In the meeting today we agreed on the following tasks:
- [x] 1. Remove the links at https://dhcr.clarin-dariah.eu/pages/news#social-media
- [x] 2. When the new version is released in production, the file content.js won't be used. Then Anna will be notified and she  can delete the entire file "content.js"  so that all resources will then be on one location. This file should then be removed: https://shared.acdh.oeaw.ac.at/dhcr/content.js

Note:
The links to the various social media accounts, are still listed here:
https://dhcr.clarin-dariah.eu/follow#social-media

@PixlTracer  @IvdL22 FYI

**Comment by patrickakk** [comment]
updated link in menu
added redirect for backwards compatibility with published link
removed usage of content.js in application

Implemented in 2023-04

Blocked until 2023-03 is released, then it can be reviewed.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer Can you review this?

**Comment by PixlTracer** [comment]
reviewed it (i.e. thumb up) but forgot to comment
-- please proceed, thank you!

**Comment by patrickakk** [comment]
ok.

blocked until 2023-04 is released. then task 2 can be started.

**Comment by patrickakk** [comment]
@PixlTracer 
(cc @IvdL22 )

Can you delete this file and then change the label to Done?

https://shared.acdh.oeaw.ac.at/dhcr/content.js

Thanks!

**Comment by PixlTracer** [comment]
done! I'll assign the label

**Comment by patrickakk** [comment]
Implemented in 2023-04
