### ISSUE TITLE
Emails from the application are rejected by Gmail

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#69]
At least one course reminder email was rejected by Gmail.

Part of the error message:
 (... indicates anonymized data)

Subject: Mail delivery failed: returning message to sender
Date: Thu, 04 May 2023 10:30:19 +0200 
....
SMTP error from remote mail server after end of data:
host gmail-smtp-in.l.google.com [142.250.27.26]:
550-5.7.26 This mail is unauthenticated, which poses a security risk to the
550-5.7.26 sender and Gmail users, and has been blocked. The sender must
550-5.7.26 authenticate with at least one of SPF or DKIM. For this message,
550-5.7.26 DKIM checks did not pass and SPF check for [clarin-dariah.eu] did
550-5.7.26 not pass with ip: [...........]. The sender should visit
550-5.7.26 https://support.google.com/mail/answer/81126#authentication for
550 5.7.26 instructions on setting up authentication. 

Actions needed:

- [x] - Check how many reminders were sent to Gmail / how many are affected
- [x] - Try if the issue can be fixed within the current process

**Comment by patrickakk** [comment]
Second error:

Subject: Mail delivery failed: returning message to sender
Date: Mon, 08 May 2023 13:25:28 +0200 
....
SMTP error from remote mail server after end of data:
host aspmx.l.google.com [...]: 550-5.7.1 [...] Messages missing a valid messageId header are not
550 5.7.1 accepted.

**Comment by patrickakk** [comment]
This also applies to invitations, reinvite and copies of those messages. It applies to all emails sent by the application to a Gmail address.

**Comment by patrickakk** [comment]
@vronk @IvdL22 @PixlTracer 
My suggestion would be to change the sender from no-reply@ to helpdesk@ 
Currently the reply-to is already helpdesk@ and we can remove that field. This was already my idea and it might solve this problem as well.

If the problem still exist after implementing this, then look further into it.

Changed label to specs missing, until it's discussed in a meeting or answered here.

**Comment by patrickakk** [comment]
discussed in meeting today, change is ok

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer @vronk 
For all the instances (prod, test, dev) the mail from address has been changed to helpdesk@. For the test and dev instance there has been added test- or dev- in front of that.
Redeployed production container. From now on the new from field will be used in production.

We can check if the problem is solved, by checking the default email box (not helpdesk) and checking if mails are rejected by gmail, for example course reminders or new user account notifications.

Blocked this item until 2023-07-13, so there are 3 weeks to check what responses come in.

After that date, and without further errors, we could close the issue?

**Comment by patrickakk** [comment]
The problem still exists, even after using the helpdesk email address as sender. (Noticed today, 2023-07-04, when the course reminders were sent).

A new solution needs to be found.

**Comment by patrickakk** [comment]
Today I've added "sender" and "return path" to the course reminder mails.
Implemented in version 2023-08/2 which will be released today.

Issue blocked until date 2023-08-05. This is the day after the next batch of reminder mails.

If it works, this solution needs to be implemented in the rest of the application as well (mailer default profile). Otherwise we need to look for another solution.

**Comment by patrickakk** [comment]
The problem still exists.

New status: looking for solution.

**Comment by patrickakk** [comment]
smtp server settings changed (repository secrets), other settings adjusted.

everything works fine in dev, test and production.

tested with a gmail account. the emails do arrive.

the final test can be on the 19th, when the next batch of course reminders is sent. we should then check the helpdesk emailaddress to see if any mails are rejected/returned.

if none, the problem could be considered as solved and we could close the issue.

blocked until 2023-09-20.

**Comment by patrickakk** [comment]
Today a new batch of course reminder mails was sent, including some Gmail addresses. All mails were delivered without rejections.

This could be reviewed by checking the inbox of the helpdesk email account. No  errors about Gmail recipients were delivered.

@IvdL22  @PixlTracer Can you change the label to Done if satisfied?

**Comment by PixlTracer** [comment]
thank you!

**Comment by patrickakk** [comment]
Implemented in 2023-09.
