### ISSUE TITLE
Find course by pre-defined tag

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#70]
During the meeting at 2023-05-17 the following new feature was suggested:

- Ability for users to find courses based on pre-defined tags
- Preferably an auto complete text field in the user interface, where only a few characters have to be typed, then the user can choose from a list of matching tags
- The tags will be pre defined in the admin area. Then lecturers can choose from this list when adding or updating a course.
- Not clear: who will be managing the list of tags? Moderators or only the admins?

@PixlTracer @IvdL22 See above the summary of the idea. Is this correct? Should something be added/changed?

**Comment by patrickakk** [comment]
Example: https://training-toolkit.sshopencloud.eu/source/529
(see at Curated topics)

**Comment by vronk** [comment]
merged #88
