### ISSUE TITLE
Avoid spaces at the beginning and end of course name

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#73]
@PixlTracer @IvdL22 @vronk 

As discussed today in the meeting:
This improves the quality of the metadata. Since those spaces can make a course name look unique although it isn't.

Proposed solution:

- When saving (add or edit/update) a course the spaces at the beginning and end will be automatically removed.
- Existing courses won't be changed. They will automatically be adapted when the user updates a course. This takes about 1,5 years to affect all courses. 
**Note:** When spaces are removed, and course names are not unique any more, this will result in an error ("This name already exists"). In that case they can send an email to the helpdesk  ;)

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer Can you review this?

It could be checked here (in dev):
https://dev-dhcr.clarin-dariah.eu/courses/add

When adding a course with leading or trailing spaces, or editing one, you can see that they are automatically removed when saving the course.

This improves the validation and makes sure that only courses with unique names are added, since adding spaces doesn't make a course unique.

Can you change the label to Done when satisfied?

**Comment by patrickakk** [comment]
Note: I've also created a small tool which removes all the spaces in public shown courses names. This can avoid problems for the contributors when updating courses.

`Note for myself:
-Run the tool once, when this is in production`

**Comment by IvdL22** [comment]
@patrickakk I have tested this but the dummy course has been added, not removed. Not sure if I tested properly.

**Comment by patrickakk** [comment]
@IvdL22 

(As explained above:)
> When adding a course with leading or trailing spaces, or editing one, you can see that they are automatically removed when saving the course.

Your dummy course has been saved in the dev instance, and I see no spaces in the course name?

The purpose of this changes is that spaces at the beginning or end of a course name are automatically removed.  So a course can be added, but just the spaces get removed. That works?

Can you change the label to Done when satisfied?

**Comment by patrickakk** [comment]
`Note for myself: The tool has been run. The leading and trailing spaces are removed from existing public shown courses.`

**Comment by PixlTracer** [comment]
I've tested it with the course name


test kjdflöajsök dfd_ ll
--
[test kjdflöajsök dfd_ ll](https://dev-dhcr.clarin-dariah.eu/courses/view/760) (and I didn't check the box 'show in the registry') -- please remove, if applicable

great work, thanks patrick! I'll set the label to done

**Comment by patrickakk** [comment]
Implemented in 2023-05.

(Since the test course is in the dev database, we can leave it there. It will disappear someday when this database is updated with a new copy from production.)
