### ISSUE TITLE
Filter doesn't adapt cities list when selecting a country

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#76]
This issue was addressed in the WG meeting at 2023-06-06.

When using the filter, selecting a country and immediately selecting a city, the list of cities contains all countries. The list is expected to be updated and contain only the cities in the selected country.
(The filter works fine).

Different behavior:
In the filter: when selecting a country, selecting a city (which is not in the country) and selecting another city, the second time, the cities list contains only the cities in the selected country.

So it looks like the updating of cities list fails at a point.

Proposed solution:
See if this can be fixed in a small amount of time. If possible, fix immediately. So assigned to July milestone.
If it turns out to be more complex; remove from July milestone and find time in the future.

**Comment by patrickakk** [comment]
This also applies for example to institutions. When selecting a country, you can also select institutions outside this country. It seems that the current sub-window with the filter options was designed in a way that the user has to close it (cross in right top corner) to apply the filters and then open it again to make the next choice. So the described issue it's not limited to only cities.

@IvdL22  @PixlTracer @vronk 
Can we talk about this in a meeting? What should be the behavior and how much priority should this issue have?

**Comment by patrickakk** [comment]
Discuss in Autumn as part of bigger review of filter process

**Comment by patrickakk** [comment]
Maybe more advanced search box instead of filter.

**Comment by patrickakk** [comment]
Removed from milestone, until review is done.

**Comment by vronk** [comment]
will be tackled in #88
