### ISSUE TITLE
Make clear difference between user roles at User->Edit page

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#79]
Currently the items for moderator and administrator roles are listed together. This can be confusing.

Change the layout so they are better separated.

**Comment by patrickakk** [comment]
The screenshot below shows the current (before) layout of the User->Edit page.

![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/4653150c-299f-4cf0-904e-ff91277557eb)

**Comment by patrickakk** [comment]
New layout:

![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/7c297b73-3902-4fd0-97f9-937b55cff3e2)

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer
Can you review this?

As of the **next day** (tomorrow) it should be visible in the test instance. (At the usual url)

Is the new layout clear and can it avoid mistakes when assigning user rights?

Can you change the label to Done if satisfied?

**Comment by IvdL22** [comment]
@patrickakk and @PixlTracer fyi: The new layout looks good. For consistency, you could write out _User administrator. What is the difference between ''administrator rights'' and ''user administrator''? I thought that one who has administrator rights automatically gets also user administrator rights. But I might be wrong.

**Comment by patrickakk** [comment]
@IvdL22 
You didn't change the label to Done?

In this case I would suggest not to write out "User administrator". 

> What is the difference between ''administrator rights'' and ''user administrator''?

This situation exists because some legacy and changes to the application made in the past. Currently both checkboxes are needed to check/uncheck, as described in the note. So it's already explained?

Right now we can choose to invest additional working hours in refactoring the application, so that only one checkbox remains.
Or, we avoid those extra hours, and You and Anna just check or uncheck **both** check-boxes when a change is made?
What do you think?

**Comment by PixlTracer** [comment]
dear both, 
I am ok with checking both boxes;
Iulianna, if this ok for you too, please change the label to 'done'

**Comment by patrickakk** [comment]
Implemented in 2023-11
