### ISSUE TITLE
Show only logentries about errors

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#81]
Add this option.

Edit 2024-11-04:

Explanation of the purpose or this issue:

In the login area it's possible to view the applications log. This allows to check if tasks are executed properly and to debug in case of problems.

Currently it's only possible to see all log messages. This includes a lot of status messages.

Preferred solution:
An option (maybe link or checkbox) which shows only the error relates messages.

**Comment by patrickakk** [comment]
`Note:` wait until available in test

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

Can you review this?

Urls:

- https://test-dhcr.clarin-dariah.eu/logentries
- https://test-dhcr.clarin-dariah.eu/logentries/errors

**Comment by PixlTracer** [comment]
hi @patrickakk 
I checked this - just a curious question: is it on purpose that there is no 'Log Entry' Tile available in the dashboard?
(This is a very nice to have, to check back whether - for instance - a course maintainer was notified; or whether a respective national mod was notified/cc'd)
I have no objections and set the label to done, thank you for this!!

**Comment by patrickakk** [comment]
@PixlTracer 
cc @IvdL22 
The feature "Log Entries" existed before, and should be available for you, as admin, in the Category Lists dashboard, here:
https://test-dhcr.clarin-dariah.eu/dashboard/category-lists

The purpose of this issue was to add
https://test-dhcr.clarin-dariah.eu/logentries/errors

This will be the place where errors are logged when the communication with Mailman / Mailing list gives errors. So preferably this list should stay empty forever ;) But now there is a place to check if there were problems.

As well the explanation on the top, about the different logtypes, on top of the page has been added.


Could you confirm if the Dashboard entry for Log Entries is also available to you? And then change to label to done again?

**Comment by IvdL22** [comment]
@patrickakk cc @PixlTracer I can view the log entries in the test instance.

**Comment by patrickakk** [comment]
@PixlTracer REMINDER: Could you confirm if the Dashboard entry for Log Entries is also available to you? And then change to label to done again?

You should be able to find it here?
https://test-dhcr.clarin-dariah.eu/dashboard/category-lists

See also:
https://github.com/acdh-oeaw/dhcr-main/issues/81#issuecomment-2478662391

**Comment by PixlTracer** [comment]
looks good, thank you - I'll set the label to done @patrickakk

**Comment by patrickakk** [comment]
Implemented in 2024-11
