### ISSUE TITLE
Map on mainpage seems to be cropped

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#82]
Splitted of from here:
https://github.com/acdh-oeaw/dhcr-main/issues/78#issuecomment-1715861676

Question from Pixeltracer;

> one minor thing: when entering the main page in dev, the map is cropped (see screenshot below); can the map be 'more zoomed in'? then the grey cropping disappears;
(if this cannot be resolved easily, please close the issue)

**Comment by patrickakk** [comment]
@PixlTracer 

Can you use this link to test it (as specified in the previous issue):
https://test-dhcr.clarin-dariah.eu/

A few questions ;) Could you quote and answer below every question?

- What monitor do you use? Normal size or extra high?
- What is size of the monitor?
- Did the browser ask for permission to use your location? What did you choose?
- Did you zoom the map (mouse scroll wheel or otherwise)?
- Do you get the preferred result when zooming in once or twice?
- Could you give some hints how I could reproduce it, as shown on your screenshot?

**Comment by patrickakk** [comment]
@PixlTracer REMINDER: Can you answer the questions above, so I can help you with this?

**Comment by PixlTracer** [comment]
> @PixlTracer
> 
> Can you use this link to test it (as specified in the previous issue): https://test-dhcr.clarin-dariah.eu/
> 
> A few questions ;) Could you quote and answer below every question?
> 
> * What monitor do you use? Normal size or extra high?
**_I am using a DELL U2518D monitor, 63,44 cm (25 inch); 2560 x 1440 resolution; the monitor on my mac has 13 inches;_** 
> * What is size of the monitor?
**_see above_**
> * Did the browser ask for permission to use your location? What did you choose?
**_no, it did not ask_**
> * Did you zoom the map (mouse scroll wheel or otherwise)?
**_no_**
> * Do you get the preferred result when zooming in once or twice?
**_yes_**
> * Could you give some hints how I could reproduce it, as shown on your screenshot?
**_no; I tried to re-create the issue/bug described above; but now everything works out just the way it should :)_**

if you have no further comments/questions left, you can assign the label 'done' and close this issue.
thanks!!

**Comment by patrickakk** [comment]
@PixlTracer 
Closing an issue is always fine. Especially since the amount of issues keeps growing.

Btw setting default center point or default zoom level can maybe done with a small amount of work. I think it can give nice results, especially when the user blocks the location access.
We could center on Europe and show more details. Please create a new issue as feature request if you need that.
