### ISSUE TITLE
Remove API v1

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#83]
As discussed in the meeting on the 13th September, the API v1 should be deprecated, as following:

- The main/landing page from API v1 should redirect to v2.
(This could be done using a 301 Moved Permanently) ?

- The endpoints should not contain any hints or JSON response indicating the new version. They should result in a 404. The redirect specified above should be enough information.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

The changes have been implemented according to the requirements specified above. Most of the changes are on the background and not directly visible.

The visible results:

API v1 landing page redirects to v2 landing page:
https://test-dhcr.clarin-dariah.eu/api/v1/

API v1 call returns a 404 / not found:
https://test-dhcr.clarin-dariah.eu/api/v1/courses/count?recent

You can find it in the test instance.

Can you change the label to Done if satisfied?

**Comment by PixlTracer** [comment]
thank you @patrickakk looks fine!

**Comment by patrickakk** [comment]
Implemented in 2023-12
