### ISSUE TITLE
Changes to course statistics

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#89]
For new courses stats on the course statistic page:

- [x] Create a link on the title, which links to the detail page.
- [x] Change amount from 15 to 25 courses
- [x] Add amount of new courses per month, for the last 1.5 year

(discussed during the meeting today, except point 2)

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

The 3 features you've requested (see first comment) are ready.

You can find them in the test instance, at Dashboard / Statistics / Course Statistics

Can you change the label to Done if satisfied?

**Comment by PixlTracer** [comment]
this is great, thank you Patrick!

**Comment by patrickakk** [comment]
Implemented in 2023-12
