### ISSUE TITLE
Unable to Login at https://test-dhcr.clarin-dariah.eu/

### ISSUE THREAD

**Issue by PixlTracer** [acdh-oeaw/dhcr-main#91]
When navigating to https://test-dhcr.clarin-dariah.eu/ the login window is shown and I enter the credentials to login: 

![dhcr test login window](https://github.com/acdh-oeaw/dhcr-main/assets/117655705/263d5553-3801-4788-b03c-e34fd18bd2f9)

1. After hitting the 'login' ('Anmelden') button, the page is loading/refreshing but no logIn is possible: 
2. instead the window pops up again (with empty description field) and I need to insert the login credentials again.

I re-do step 1. then step 2. follows and I am caught in an endless loop...

latest attempt to login (from ACDH-CH/OeAW) was today, 2.10.23 at around 13.00 with chrome on MacOS.

**Comment by patrickakk** [comment]
@PixlTracer 
The username shows as first character the "d", that's the wrong one ;)

Did you use the correct credentials?

When using wrong credentials there should be a loop or no access.

Can you change the label to "Done" if you can login using the correct credentials?

**Comment by PixlTracer** [comment]
ok, I change the label to done and close the issue
