### ISSUE TITLE
Add ability to manage countries in the login area

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#92]
The tile "Category Lists" in the login area contains possibilities to manage various items (City, Institution, etc.)

Currently the countries are not available here. In the last months it occurred a few times that changes needed to be made (additions). So adding that option to the user interface would make it easier.

Added to November milestone to check if this can be done in a small amount of time. Otherwise it will be removed from that milestone.

@PixlTracer  @IvdL22 See above FYI.

**Comment by IvdL22** [comment]
Hi @patrickakk Patrick, as suggested by email, I am adding here the list of countries that we could use: https://gist.github.com/svarlamov/0e99492484ac0a853fe522f4d7ce3792

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 
Do you agree that, after adding the list specified above, we can close this issue without developing the additional feature, as described on top?
This could save valuable development hours?

(I've moved this issue to the February milestone, to keep it "in focus" feel free to suggest otherwise if you have a better idea).

**Comment by PixlTracer** [comment]
@patrickakk @IvdL22 ok

**Comment by patrickakk** [comment]
@IvdL22 now waiting for your response?

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 
I've checked this, and noticed there since a lot of countries are already present, there would be duplicates and differences.

Probably adding a user interface item for this category as described in the first post would be a good approach.

Moved back to 2024 milestone, were the issue came from.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

The feature you've requested is ready.

In Dashboard / Category lists there is a new entry "Countries" available. Only available to administrators. You can view, add and edit countries there. Also validation was added, to prevent duplicate country names.

You can start testing and find the available options here:
https://test-dhcr.clarin-dariah.eu/dashboard/category-lists

Can you change the label to Done if satisfied?

**Comment by IvdL22** [comment]
@patrickakk  and @PixlTracer  in cc: I have tried to access the test environment but the previous username does not work anymore. I am required to give an email address. Has anything changed? Please let me know by email.

**Comment by patrickakk** [comment]
@IvdL22 
The credentials for the test instance are the same as always. I've sent you an email.

**Comment by IvdL22** [comment]
@patrickakk I have review the countries category and tested adding a duplicate country. Everything works fine. Thank you.

**Comment by patrickakk** [comment]
Implemented in 2024-05
