### ISSUE TITLE
Include additional information in the course reminders

### ISSUE THREAD

**Issue by IvdL22** [acdh-oeaw/dhcr-main#95]
Please include the following information  either in the main content or at the bottom of the course reminders:

_If the course does not take place anymore, please unpublish it (**Go to your Dashboard -> My Courses -> Edit -> Uncheck publish**).
If the course is still running but you wish to transfer the course ownership to a fellow lecturer, please let us know by replying to this email with the details of the lecturer._

**Comment by patrickakk** [comment]
Removed this existing text from the course reminders mail: "In case your course or programme does not take place anymore, please uncheck the box "Show course in the registry"."

**Comment by patrickakk** [comment]
Added the text specified above to the course reminders mail. As well as in "My Courses".

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

The feature you've requested is ready.

You can find it in the test instance.

- At Dashboard, My Couses, I've added text. For this I needed to adapt your text. Can you check that?
- In the course reminders mail, some text has been removed as specified above and the new text has been added.
You can check that text here:
https://github.com/acdh-oeaw/dhcr-main/blob/test/templates/email/text/course_reminders/reminder.php


Can you change the label to Done if satisfied?

**Comment by PixlTracer** [comment]
thank you @patrickakk

**Comment by patrickakk** [comment]
Implemented in 2023-12
