### ISSUE TITLE
Add server-side start date validation

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#96]
Al tough the JavaScript pop-up does validation, it seems to be possible to enter an invalid date, when entering a new course, see screenshot. 
![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/3ecafd44-7c6c-4542-b9b3-e3b67cbc667d)

**Comment by patrickakk** [comment]
Note: I've converted the date to a valid format, so the NaN disappeared now. The bug remains.

**Comment by patrickakk** [comment]
Proposed solution:
Require JavaScript for the course add and edit page.

**Comment by patrickakk** [comment]
Waiting for bug report.

**Comment by patrickakk** [comment]
No bug report received.

**Comment by patrickakk** [comment]
New solution: Add server-side start date validation

All the start dates provided by the user will be checked, one by one, on the server side. This makes it independent from JavaScript or other browser or user dependent items.

Note: default validation by the framework wasn't possible since this field is an array converted to and stored as a string (legacy).

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 
The validation has been implemented. Visible items for the users are:

# New explanation
![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/b87782fb-abc4-4f07-8212-2c8a1a3a7b55)

# Updated error message
![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/2856d5df-072c-4d1c-a77a-eccce3d0cd2a)

# Explanation at field
![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/22bbe9ad-45d5-45a1-8554-4f2213d58652)


It will be available in the test instance tomorrow. (Not today).

Can you change the label to Done if you agree with the solution?

**Comment by IvdL22** [comment]
great, thank you @patrickakk

**Comment by patrickakk** [comment]
Implemented in 2024-05
