### ISSUE TITLE
Moderator does not receive notification of new course

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#97]
When a new course is added, an email notification should be sent, so that the national moderator can approve the course.

For Belgium the notification was not received. Example: course ID 798

The notifications has been sent to the admins instead.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

The problem seems to be solved. I've tested it myself in the test instance, by removing the moderator for the Netherlands, assigning myself as moderator for the Netherlands, creating a test course for an institution in the Netherlands.
The result was: the notification mail with the request to approve was only sent to the moderator (me) and not to the admins.
After that I reverted the changes.

Do you want to test it in the test instance as well?

**Comment by PixlTracer** [comment]
dear Patrick, 
thank you for taking the time to test this yourself; 
I do trust your skills -- since you tested it and said it is working fine, I'd opt to proceed and set the label of this issue to 'done';
@IvdL22 if you have no further comments, please assign the label 'done' - thank you!

**Comment by IvdL22** [comment]
@PixlTracer @patrickakk All good, thank you.

**Comment by patrickakk** [comment]
Implemented in 2024-02

**Comment by patrickakk** [comment]
@fosco13 Nice that you also want to test this. I'll send you the details of the test instance per mail. Looking forward to your reply here.

**Comment by patrickakk** [comment]
@fosco13 Closing the issue again, since no feedback received.

Latest status: The feature is in production and working fine.
